server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active:
      - git

  kafka:
    bootstrap-servers: kafka1:29092

  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/SKY-HORSE-MAN-POWER/INFRA_config.git
          default-label: main
          username: ${username}
          password: ${password}
          search-paths:
            - auction-service
            - member-service
            - chat-service
        encrypt:
          enabled: false

encrypt:
  key: ${key}