name: Config server CI with gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.cloud.config.server.git.username: ${{ secrets.GIT_USERNAME }}
          spring.cloud.config.server.git.password: ${{ secrets.GIT_PASSWORD }}
          encrypt.key: ${{ secrets.ENCRYPT_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/config-server .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/config-server

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/config-server

      - name: docker stop container
        run: sudo docker stop config-server

      - name: docker run new container
        run: sudo docker run -d --name config-server --rm -p 8071:8071 --net cheonma-network ${{ secrets.DOCKERHUB_USERNAME }}/config-server

      - name: delete old docker image
        run: sudo docker system prune -f